name: Deploy Laravel Project

on:
  push:
    branches:
      - main  # Change to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install Node.js dependencies
        run: npm install

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Migrate and seed database
        run: |
          php artisan migrate --seed
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: root

      - name: Run tests
        run: php vendor/bin/phpunit

      - name: Build assets
        run: npm run dev

      # Add additional steps for deployment if needed
      # e.g., deploying to a server or cloud service
